name: "feature-release"

on:
  push:
    tags:
      - "v*"

jobs:
  feature-release:
    name: "feature-release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: "Build & test"
        run: |
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.RELEASE_TOKEN }}"
          prerelease: false
          files: |
            LICENSE.txt
            *.jar
