name: feature release
run-name: ${{ github.actor }} is deploying feature-01
on:
  push:
    branches:
      - v.*.*.*
jobs:
  ci-feature-01:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Ser environtmet var
        run: echo "TAG_NAME=${{REF_NANE:ref/heads/#}}" >> $GITHUB_ENV
      - run: |
          git config --global user.email "${{ github.event.pusher.email }}"
          git config --global user.name "${{ github.actor }}"
      - name: release main
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
