name: feature release
run-name: ${{ github.actor }} is deploying feature-01
on:
  push:
    branches:
      - "v.*.*.*"
jobs:
  ci-feature-01:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "release.tar.gz,foo/*.txt"
          bodyFile: "body.md"
          token: ${{ secrets.RELEASE_TOKEN }}
